# Generated by Django 2.1.5 on 2021-09-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.FileField(upload_to='Actualizaciones de Horarios de profesores/')),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoExcelHorariosLaboratorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.FileField(upload_to='Actualizaciones de Horarios de Laboratorios/')),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoExcelUbicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.FileField(upload_to='Actualizaciones de Ubicaciones/')),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionCasilleros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.FileField(upload_to='Asignacion Casilleros/')),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.FileField(upload_to='Calendario estudiantil/')),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorariosLaboratorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=255, null=True)),
                ('lunes', models.TextField(blank=True, max_length=255, null=True)),
                ('martes', models.TextField(blank=True, max_length=255, null=True)),
                ('miercoles', models.TextField(blank=True, max_length=255, null=True)),
                ('jueves', models.TextField(blank=True, max_length=255, null=True)),
                ('viernes', models.TextField(blank=True, max_length=255, null=True)),
                ('sabado', models.TextField(blank=True, max_length=255, null=True)),
                ('domingo', models.TextField(blank=True, max_length=255, null=True)),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorariosProfesores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='Nombre', max_length=255)),
                ('lunes', models.TextField(blank=True, max_length=255, null=True)),
                ('martes', models.TextField(blank=True, max_length=255, null=True)),
                ('miercoles', models.TextField(blank=True, max_length=255, null=True)),
                ('jueves', models.TextField(blank=True, max_length=255, null=True)),
                ('viernes', models.TextField(blank=True, max_length=255, null=True)),
                ('sabado', models.TextField(blank=True, max_length=255, null=True)),
                ('domingo', models.TextField(blank=True, max_length=255, null=True)),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.FileField(upload_to='Pensum/')),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=15, max_digits=20)),
                ('longitud', models.DecimalField(blank=True, decimal_places=15, max_digits=20)),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
