# Generated by Django 2.1.5 on 2021-09-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.FileField(upload_to='Actividades Extracuriculares/')),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
