# Generated by Django 2.1.5 on 2021-10-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0003_normatividadarchivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normatividadarchivo',
            name='documento',
            field=models.FileField(upload_to='Normatividad/'),
        ),
    ]
