# Generated by Django 2.1.5 on 2021-10-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0004_auto_20211005_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoFrecArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.FileField(upload_to='No frecuencia/')),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
