# Generated by Django 2.1.5 on 2021-10-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0005_nofrecarchivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normatividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.TextField(max_length=255)),
                ('pregunta', models.TextField(max_length=255, null=True)),
                ('respuesta', models.TextField(max_length=255, null=True)),
                ('complemento', models.TextField(blank=True, max_length=255, null=True)),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
