# Generated by Django 2.1.5 on 2021-10-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0007_nofrec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nofrec',
            old_name='info',
            new_name='respuesta',
        ),
    ]
