# Generated by Django 2.1.5 on 2021-11-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0009_mensajemasivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo1',
            field=models.TextField(default='¿Como preguntarían los usuarios por esta intención?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo10',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo2',
            field=models.TextField(default='¿Como preguntarían los usuarios por esta intención?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo3',
            field=models.TextField(default='¿Como preguntarían los usuarios por esta intención?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo4',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo5',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo6',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo7',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo8',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo9',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo1',
            field=models.TextField(default='¿Como preguntarían los usuarios por esta intención?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo10',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo2',
            field=models.TextField(default='¿Como preguntarían los usuarios por esta intención?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo3',
            field=models.TextField(default='¿Como preguntarían los usuarios por esta intención?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo4',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo5',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo6',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo7',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo8',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo9',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
