# Generated by Django 2.1.5 on 2021-11-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0010_auto_20211108_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo11',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo12',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo13',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo14',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nofrec',
            name='ejemplo15',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo11',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo12',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo13',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo14',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normatividad',
            name='ejemplo15',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
