# Generated by Django 3.2.9 on 2021-12-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0011_auto_20211108_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoFrec',
        ),
        migrations.DeleteModel(
            name='NoFrecArchivo',
        ),
    ]
