# Generated by Django 3.2.9 on 2021-12-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0012_auto_20211215_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.FileField(upload_to='Reglamento/')),
                ('ultimaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
